### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by miversen33** [akasuv/neoland#10]
Before I get into my requests, I just wanted to say that this is a fantastic website! 
I can break my requests up into individual "issues", I just figured I would float them and see if there was any interest before doing so

- [ ] Expose an API so the plugins in neoland can be queried via third party
        - Justification
          - By exposing a way to access the plugin data underneath neoland, we (developers) can use neoland as a sort of agregator. Since the hard work of "gathering" the data on github has been complete (and its properly tagged, etc), it would make further extensions of plugin management easier, as opposed to developers having to metaphorically "reinvent the wheel"
- [ ] Add a "Feeling Lucky" style button to take a user to a random plugin
        - Justification
            - Lets be honest, when you are trying plugins and exploring the world of neovim, alot of times you don't know what you are missing because you have no idea it exists. While [/r/neovim](https://reddit.com/neovim) does a good job of exposing users to new plugins, it would be equally as interesting to have a button that just takes you to a randomly selected plugin
- [ ] "Sort" listed plugins by stars (or some other ish measurable way of measuring popularity)
        - Justification
            - While the above is about exposing users to new plugins, it is just as useful to show users what "everyone" is using. Having the plugin list (filtered or not) rank in some defined (not hidden) way would help newer users see that "X plugin is really popular for solving Y problem"

Again, thank you for this!

**Comment by akasuv** [comment]
Hey @miversen33, thanks for the feedback! To answer your questions:
1. About the API, I'm considering it, but for now I'm focusing on building the site, so the API part won't get delivered very quickly
2. 'Feeling Lucky' feature is a very brilliant idea, I'll give it a try
3. Sorting is already on the plan list, NeoLand will also have like 'New', 'The Best', and 'Must install' sections, so stay tuned 🤞!

**Comment by miversen33** [comment]
> Hey @miversen33, thanks for the feedback! To answer your questions:
> 1. About the API, I'm considering it, but for now I'm focusing on building the site, so the API part won't get delivered very quickly

No problem! As this is open source and I'm getting bored with my current projects, would you be against a draft PR to mock out what such an API would look like? I have a new project idea in mind and having an easy to query API for neovim plugins would make it easier :) I was planning on making such a thing myself anyway, so if there is an existing tool (such as this) that I can contribute it to instead of being my own thing, I would love to do so

**Comment by akasuv** [comment]
That would be great! I'm open to any kind of PR

**Comment by chrisgrieser** [comment]
>  Expose an API so the plugins in neoland can be queried via third party

just wanted to add my support for this. As soon as there is an API / some JSON file listing all plugins, I'll add it to my Alfred plugin for neovim, for example! :)

**Comment by miversen33** [comment]
I've created a branch of this specifically to try and map out what the API might look like. I have not spent much time writing typescript before (I usually am working in a more backend oriented language such as python) so it will take some time before I have anything besides a markdown put together. 

@akasuv would you prefer I open a Draft PR to discuss the API or would you prefer it here?

Also, should I close this issue and create separate ones?

**Comment by akasuv** [comment]
Let's create a PR!
