### ISSUE TITLE
Add danielfalk/smart-open.nvim

### ISSUE THREAD

**Issue by danielfalk** [akasuv/neoland#11]
## Plugin name
smart-open.nvim

## Description
Smart file fuzzy finder that adapts to your usage and improves suggestions over time.

## Repo link
https://github.com/danielfalk/smart-open.nvim

## Tags
`Fuzzy Finder`

---
Tag reference:
`Plugin Manager` `LSP` `Completion` `Language` `Syntax` `Snippet` `Register` `Marks` `Search` `Fuzzy Finder` `File Explorer` `Project` `Color` `Colorscheme` `Bars and Lines` `Startup` `Icon` `Media` `Note Taking` `Utility` `Terminal Integration` `Debugging` `Test` `Code Runner` `Neovim Lua Development` `Fennel` `Dependency Management` `Git` `Motion` `Keybinding` `Mouse` `Scrolling` `Editing Support` `Formatting` `Command Line` `Session` `Remote Development` `Split and Window` `Game` `Preconfigured Configuration` `Version Manager` `Programming Languages Support`

**Comment by akasuv** [comment]
Hey @danielfalk, your plugin is on NeoLand! Check it here https://neoland.dev/plugin/2176
