### ISSUE TITLE
Add `idanarye/nvim-moonicipal`

### ISSUE THREAD

**Issue by idanarye** [akasuv/neoland#14]
## Plugin name

Moonicipal

## Description

Moonicipal is a task runner that focuses on personal tasks that are easy to
write and to change:

* Task files are personal - users can edit them without breaking the workflow for other developers that use the same project.
* Tasks are Lua functions that run inside Neovim - they can can easily access all of Neovim's context and functionalities, and easily interact with other Neovim plugins.
* The task functions always run in coroutines, and some helpers are provided for writing async code instead of using callbacks.
* The task file is reloaded each time a user runs a task, so it can be edited rapidly.
* Caching facilities for saving things like build configuration or test/example-to-run without having to change the tasks file each time.

## Repo link

https://github.com/idanarye/nvim-moonicipal

## Tags

`Task Runner`

---

Tag reference:

`Bars and Lines` `Code Runner` `Color` `Colorscheme` `Command Line` `Completion` `Debugging` `Dependency Management` `Editing Support` `Fennel` `File Explorer` `Formatting` `Fuzzy Finder` `Game` `Git` `Icon` `Keybinding` `LSP` `Language` `Marks` `Media` `Motion` `Mouse` `Neovim Lua Development` `Note Taking` `Plugin Manager` `Preconfigured Configuration` `Programming Languages Support` `Project` `Register` `Remote Development` `Scrolling` `Search` `Session` `Snippet` `Split and Window` `Startup` `Syntax` `Terminal Integration` `Test` `Utility` `Version Manager`

**Comment by akasuv** [comment]
Hey @idanarye, your plugin is on NeoLand! Check it [here](https://neoland.dev/plugin/2179)
