### ISSUE TITLE
Add `idanarye/nvim-channelot`

### ISSUE THREAD

**Issue by idanarye** [akasuv/neoland#15]
## Plugin name

Channelot

## Description

Channelot is a library plugin for operating Neovim jobs from a Lua coroutine. It supports:

* Starting jobs, with and without terminals.
* Starting multiple jobs on the same Neovim terminal.
* Job control is done via Lua coroutines - Channelot will resume the coroutine once the job is finished and/or when it outputs new data.

Channelot was created as a supplemental plugin for [Moonicipal](https://github.com/idanarye/nvim-moonicipal), but can be used independent of it.

## Repo link

https://github.com/idanarye/nvim-channelot

## Tags

`Terminal` `Jobs`

---

Tag reference:

`Bars and Lines` `Code Runner` `Color` `Colorscheme` `Command Line` `Completion` `Debugging` `Dependency Management` `Editing Support` `Fennel` `File Explorer` `Formatting` `Fuzzy Finder` `Game` `Git` `Icon` `Keybinding` `LSP` `Language` `Marks` `Media` `Motion` `Mouse` `Neovim Lua Development` `Note Taking` `Plugin Manager` `Preconfigured Configuration` `Programming Languages Support` `Project` `Register` `Remote Development` `Scrolling` `Search` `Session` `Snippet` `Split and Window` `Startup` `Syntax` `Terminal Integration` `Test` `Utility` `Version Manager`

**Comment by akasuv** [comment]
Hey @idanarye, your plugin is on NeoLand! Check it [here](https://neoland.dev/plugin/2181).
