### ISSUE TITLE
Add `idanarye/nvim-buffls`

### ISSUE THREAD

**Issue by idanarye** [akasuv/neoland#16]
## Plugin name

BuffLS

## Description

BuffLS is a [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) source for adding LSP-like functionality for a specific buffer. This is useful for small scripts that use Neovim buffers for input, and want to enhance their UX with things like custom completion or code actions. Writing a separate null-ls source for each such script is too cumbersome, so BuffLS acts as a single source that redirects the LSP requests to objects stored in a buffer variable.

BuffLS was created as a supplemental plugin for [Moonicipal](https://github.com/idanarye/nvim-moonicipal), but can be used independent of it.

## Repo link

https://github.com/idanarye/nvim-buffls

## Tags

`LSP` `Editing Support`

---

Tag reference:

`Bars and Lines` `Code Runner` `Color` `Colorscheme` `Command Line` `Completion` `Debugging` `Dependency Management` `Editing Support` `Fennel` `File Explorer` `Formatting` `Fuzzy Finder` `Game` `Git` `Icon` `Keybinding` `LSP` `Language` `Marks` `Media` `Motion` `Mouse` `Neovim Lua Development` `Note Taking` `Plugin Manager` `Preconfigured Configuration` `Programming Languages Support` `Project` `Register` `Remote Development` `Scrolling` `Search` `Session` `Snippet` `Split and Window` `Startup` `Syntax` `Terminal Integration` `Test` `Utility` `Version Manager`

**Comment by akasuv** [comment]
Hey @idanarye, your plugin is on NeoLand! Check it [here](https://neoland.dev/plugin/2180).
