### ISSUE TITLE
New plugin "web-dev.nvim"

### ISSUE THREAD

**Issue by jonathandion** [akasuv/neoland#17]
## Plugin name

web-dev.nvim

## Description

Small Neovim configuration written in Lua that is specifically designed for web development.

## Repo link

https://github.com/jonathandion/web-dev.nvim

## Tags

`Preconfigured Configuration`

**Comment by akasuv** [comment]
Hey @jonathandion, your plugin is on NeoLand! https://neoland.dev/plugin/2182
