### ISSUE TITLE
New plugin

### ISSUE THREAD

**Issue by maxmx03** [akasuv/neoland#18]
## Plugin name

Dracula.nvim

## Description

Dracula.nvim is a port of the popular Dracula colorscheme for Neovim,

## Repo link

https://github.com/maxmx03/dracula.nvim

## Tags

---

Tag reference:

`Dracula` `semantic highlight` `treesitter colorscheme` `colorscheme` `Colorscheme`

**Comment by akasuv** [comment]
Hi, @maxmx03, your plugin is on NeoLand! https://neoland.dev/plugin/2183
