### ISSUE TITLE
New plugin Aaronik/GPTModels.nvim

### ISSUE THREAD

**Issue by aaronik** [akasuv/neoland#20]
## Plugin name
GPTModels.nvim

## Description
GPTModels - a stable, clean, multi model, window based LLM AI plugin for neovim

## Repo link
https://github.com/Aaronik/GPTModels.nvim
## Tags
`Editing Support` `Programming Languages Support`
---

Tag reference:

`Bars and Lines` `Code Runner` `Color` `Colorscheme` `Command Line` `Completion` `Debugging` `Dependency Management` `Editing Support` `Fennel` `File Explorer` `Formatting` `Fuzzy Finder` `Game` `Git` `Icon` `Keybinding` `LSP` `Language` `Marks` `Media` `Motion` `Mouse` `Neovim Lua Development` `Note Taking` `Plugin Manager` `Preconfigured Configuration` `Programming Languages Support` `Project` `Register` `Remote Development` `Scrolling` `Search` `Session` `Snippet` `Split and Window` `Startup` `Syntax` `Terminal Integration` `Test` `Utility` `Version Manager`

**Comment by aaronik** [comment]
Updated to remove AI tag, which isn't in the reference. If that's not important though, I'd love to add it back.

**Comment by aaronik** [comment]
@akasuv Do you think this can be merged in?

**Comment by akasuv** [comment]
Hey @Aaronik thanks for the PR! I'll review it in the next week 😁

**Comment by aaronik** [comment]
Hey @akasuv any update on this?

**Comment by akasuv** [comment]
Hi @Aaronik your plugin is live on NeoLand! https://neoland.dev/plugin/8844
