### ISSUE TITLE
New plugin: just.nvim

### ISSUE THREAD

**Issue by nxuv** [akasuv/neoland#21]
## Plugin name
just.nvim

## Description
Task runner for justfiles

## Repo link
https://github.com/al1-ce/just.nvim

## Tags
`Code Runner`
---

Tag reference:

`Bars and Lines` `Code Runner` `Color` `Colorscheme` `Command Line` `Completion` `Debugging` `Dependency Management` `Editing Support` `Fennel` `File Explorer` `Formatting` `Fuzzy Finder` `Game` `Git` `Icon` `Keybinding` `LSP` `Language` `Marks` `Media` `Motion` `Mouse` `Neovim Lua Development` `Note Taking` `Plugin Manager` `Preconfigured Configuration` `Programming Languages Support` `Project` `Register` `Remote Development` `Scrolling` `Search` `Session` `Snippet` `Split and Window` `Startup` `Syntax` `Terminal Integration` `Test` `Utility` `Version Manager`

**Comment by akasuv** [comment]
Hi @al1-ce your plugin is live on NeoLand! https://neoland.dev/plugin/8843
