### ISSUE TITLE
New plugin: `karshPrime/only-tmux.nvim`

### ISSUE THREAD

**Issue by karshPrime** [akasuv/neoland#22]
## Plugin name
karshPrime/only-tmux.nvim

## Description
Neovim plugin to minimise (move to a new window) or close all other panes but the current Nvim pane, whilist also minimising all other nvim panes to buffer, to have just the current pane cover the whole screen; focused mode.

## Repo link
https://github.com/karshPrime/only-tmux.nvim

## Tags
`Motion` `Split and Window` `Keybinding` `Terminal Integration`

**Comment by akasuv** [comment]
Hi @karshPrime your plugin is live on NeoLand! https://neoland.dev/plugin/8842
