### ISSUE TITLE
New plugin: `karshPrime/tmux-compile.nvim`

### ISSUE THREAD

**Issue by karshPrime** [akasuv/neoland#23]
## Plugin name
tmux-compile.nvim

## Description
With this plugin you could set a key, say `F5` to run/compile any of your project with your configuration. Run `make` for C projects, `cargo build` for rust, `go build` for Go, and so on; with same key. It uses tmux to run/build project in same window (new pane) or in a new background window.

## Repo link
https://github.com/karshPrime/tmux-compile.nvim

## Tags
`Split and Window` `Code Runner` `Keybinding` `Programming Languages Support` `Terminal Integration`

**Comment by akasuv** [comment]
Hi @karshPrime your plugin is live on NeoLand! https://neoland.dev/plugin/8841
