### ISSUE TITLE
kustomize.nvim

### ISSUE THREAD

**Issue by Allaman** [akasuv/neoland#4]
## Plugin name

kustomize.nvim

## Description

 A Neovim plugin with some useful functions for working with Kustomize 

## Repo link

https://github.com/Allaman/kustomize.nvim

## Tags

`Programming Languages Support` `Debugging` `Terminal Integration`

**Comment by akasuv** [comment]
Hey @Allaman, your plugin is on NeoLand! Check it here https://neoland.dev/plugin/2172
