### ISSUE TITLE
Plugin submission checklist

### ISSUE THREAD

**Issue by cbochs** [akasuv/neoland#6]
I've noticed that there isn't (yet) a checklist or set of guidelines for authors submitting their plugins to follow when creating a Submit Plugin issue. Might be good to add something similar to awesome-neovim's checklist? https://github.com/rockerBOO/awesome-neovim/blob/main/.github/pull_request_template.md

**Comment by akasuv** [comment]
Hey @cbochs, thanks for the feedback! I'm thinking of a more automatic way for authors to submit plugins, but I'll keep this one as a backup.
