### ISSUE TITLE
Add `cbochs/grapple.nvim`

### ISSUE THREAD

**Issue by cbochs** [akasuv/neoland#7]
## Plugin name

grapple.nvim

## Description

Provides tagging, cursor tracking, and immediate navigation to important project files.

## Repo link

https://github.com/cbochs/grapple.nvim

## Tags

`Marks` 

---
Tag reference:
`Plugin Manager` `LSP` `Completion` `Language` `Syntax` `Snippet` `Register` `Marks` `Search` `Fuzzy Finder` `File Explorer` `Project` `Color` `Colorscheme` `Bars and Lines` `Startup` `Icon` `Media` `Note Taking` `Utility` `Terminal Integration` `Debugging` `Test` `Code Runner` `Neovim Lua Development` `Fennel` `Dependency Management` `Git` `Motion` `Keybinding` `Mouse` `Scrolling` `Editing Support` `Formatting` `Command Line` `Session` `Remote Development` `Split and Window` `Game` `Preconfigured Configuration` `Version Manager` `Programming Languages Support`

**Comment by akasuv** [comment]
Hey @cbochs, your plugin is on NeoLand! Check it here https://neoland.dev/plugin/2174
