### ISSUE TITLE
Add `cbochs/portal.nvim`

### ISSUE THREAD

**Issue by cbochs** [akasuv/neoland#8]
## Plugin name

portal.nvim

## Description

Build upon and enhance existing jumplist motions (i.e. `<c-i>` and `<c-o>`).

## Repo link

https://github.com/cbochs/portal.nvim

## Tags

`Motion` `Utility`

---
Tag reference:
`Plugin Manager` `LSP` `Completion` `Language` `Syntax` `Snippet` `Register` `Marks` `Search` `Fuzzy Finder` `File Explorer` `Project` `Color` `Colorscheme` `Bars and Lines` `Startup` `Icon` `Media` `Note Taking` `Utility` `Terminal Integration` `Debugging` `Test` `Code Runner` `Neovim Lua Development` `Fennel` `Dependency Management` `Git` `Motion` `Keybinding` `Mouse` `Scrolling` `Editing Support` `Formatting` `Command Line` `Session` `Remote Development` `Split and Window` `Game` `Preconfigured Configuration` `Version Manager` `Programming Languages Support`

**Comment by akasuv** [comment]
Hey @cbochs, your plugin is on NeoLand! Check it here https://neoland.dev/plugin/2175
